In [1]:
#import the libraries
import pandas as pd
import scipy 
import numpy as np
from scipy import stats

In [2]:
buyer=pd.read_csv('BuyerRatio.csv')

In [3]:
buyer

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [4]:
#Contigency Table
cont=[[50,142,131,70],[435,1523,1356,750]]
cont

[[50, 142, 131, 70], [435, 1523, 1356, 750]]

In [5]:
from scipy.stats import chi2_contingency

In [7]:
stat, p, dof, expected = chi2_contingency(cont) 
print (stat, p, dof, expected)

1.595945538661058 0.6603094907091882 3 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [8]:
print("===Chi2 Stat===")
print(stat)
print("\n")
print("===Degrees of Freedom===")
print(dof)
print("\n")
print("===P-Value===")
print(p)
print("\n")
print("===Contingency Table===")
print(expected)

===Chi2 Stat===
1.595945538661058


===Degrees of Freedom===
3


===P-Value===
0.6603094907091882


===Contingency Table===
[[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]
