In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [2]:
# import some data to play with
iris = pd.read_csv('iris.csv')

In [3]:
#Complete Iris dataset
label_encoder=preprocessing.LabelEncoder()
iris.Species=label_encoder.fit_transform(iris['Species'])

In [4]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [5]:
array = iris.values
X = array[:,0:3]
y = array[:,3]

In [6]:
X

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4],
       [5.4, 3.9, 1.7],
       [4.6, 3.4, 1.4],
       [5. , 3.4, 1.5],
       [4.4, 2.9, 1.4],
       [4.9, 3.1, 1.5],
       [5.4, 3.7, 1.5],
       [4.8, 3.4, 1.6],
       [4.8, 3. , 1.4],
       [4.3, 3. , 1.1],
       [5.8, 4. , 1.2],
       [5.7, 4.4, 1.5],
       [5.4, 3.9, 1.3],
       [5.1, 3.5, 1.4],
       [5.7, 3.8, 1.7],
       [5.1, 3.8, 1.5],
       [5.4, 3.4, 1.7],
       [5.1, 3.7, 1.5],
       [4.6, 3.6, 1. ],
       [5.1, 3.3, 1.7],
       [4.8, 3.4, 1.9],
       [5. , 3. , 1.6],
       [5. , 3.4, 1.6],
       [5.2, 3.5, 1.5],
       [5.2, 3.4, 1.4],
       [4.7, 3.2, 1.6],
       [4.8, 3.1, 1.6],
       [5.4, 3.4, 1.5],
       [5.2, 4.1, 1.5],
       [5.5, 4.2, 1.4],
       [4.9, 3.1, 1.5],
       [5. , 3.2, 1.2],
       [5.5, 3.5, 1.3],
       [4.9, 3.6, 1.4],
       [4.4, 3. , 1.3],
       [5.1, 3.4, 1.5],
       [5. , 3.5, 1.3],
       [4.5, 2.3

In [7]:
y

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=40)

In [11]:
# Decision Tree Regression
from sklearn.tree import DecisionTreeRegressor

In [12]:
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [13]:
preds=model.predict(X_test)

In [14]:
preds

array([0.2, 1.2, 1.8, 2. , 1.1, 2.3, 1.3, 1.3, 1.2, 0.2, 1.3, 0.2, 0.2,
       1.8, 1.2, 2.4, 1.5, 2.4, 1.8, 1.2, 1.9, 2.3, 1.1, 0.2, 1.3, 0.4,
       0.2, 2. , 0.2, 1.1, 1.1, 0.2, 0.2, 0.2, 0.2, 1.9, 0.2, 0.2, 2. ,
       0.2, 0.2, 1.4, 1.5, 2.3, 2.3])

In [15]:
pd.crosstab(preds,y_test)

col_0  0.1  0.2  0.3  0.4  0.5  1.0  1.2  1.3  1.4  1.5  1.8  2.0  2.1  2.2  \
row_0                                                                         
0.2      0    1    2    0    0    0    0    0    0    0    0    0    0    0   
0.2      2    6    1    2    1    0    0    0    0    0    0    0    0    0   
0.4      0    0    1    0    0    0    0    0    0    0    0    0    0    0   
1.1      0    0    0    0    0    2    0    2    0    0    0    0    0    0   
1.2      0    0    0    0    0    1    0    0    1    2    0    0    0    0   
1.3      0    0    0    0    0    0    1    2    0    1    0    0    0    0   
1.4      0    0    0    0    0    0    0    0    0    1    0    0    0    0   
1.5      0    0    0    0    0    0    0    0    0    0    2    0    0    0   
1.8      0    0    0    0    0    0    0    0    1    0    1    0    0    0   
1.9      0    0    0    0    0    0    0    0    0    0    0    0    1    1   
2.0      0    0    0    0    0    0    0    0    0    0    1    1    0    1   
2.3      0    0    0    0    0    0    0    0    0    0    1    0    2    0   
2.4      0    0    0    0    0    0    0    0    0    0    0    0    1    0   

col_0  2.3  2.4  2.5  
row_0                 
0.2      0    0    0  
0.2      0    0    0  
0.4      0    0    0  
1.1      0    0    0  
1.2      0    0    0  
1.3      0    0    0  
1.4      0    0    0  
1.5      0    0    0  
1.8      1    0    0  
1.9      0    0    0  
2.0      0    0    0  
2.3      0    1    0  
2.4      0    0    1

In [16]:
np.mean(preds==y_test)

0.2222222222222222